version: "3.8"

services:
  opcplc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opcplc
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./opcua_certs/certs:/app/pki
      - ./res/customized_node:/app/customized
    restart: unless-stopped
    networks:
      - opc_network

  client:
    image: alpine:latest
    container_name: client
    networks:
      - opc_network
    volumes:
      - ./client_certs:/app
    entrypoint: ["sleep", "infinity"]

networks:
  opc_network:
    driver: bridge
    name: opc_network
