apiVersion: apps/v1
kind: Deployment
metadata:
  name: opc-deployment
  namespace: jack-dev
  labels:
    app: opc-simulator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opc-simulator
  template:
    metadata:
      labels:
        app: opc-simulator
    spec:
      containers:
        - name: opc-simulator-server-container
          image: iot.azurecr.io/opc-plc:opc-plc
          args:
            - "--pn=80"
            - "--ll=debug"
            - "--sn=5"
            - "--sr=10"
            - "--st=uint"
            - "--fn=5"
            - "--ft=uint"
            - "--gn=5"
            - "--ap=app/pki/"
          ports:
            - name: tcp-port
              containerPort: 80
            - name: http-port
              containerPort: 8080
      imagePullSecrets:
        - name: res
