apiVersion: v1
kind: Service
metadata:
  name: opc-simulator-service
  namespace: dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: opc-simulator
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
