apiVersion: v1
kind: Service
metadata:
  name: opc-plc-service
  namespace: jack-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "http"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"

spec:
  selector:
    app: opc-simulator
  externalTrafficPolicy: Local
  ports:
    - name: tcp-service-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http

  type: LoadBalancer
