trigger:
  - none

parameters:
  - name: dockerfilePath
    displayName: Dockerfile Path
    type: string
    default: ./Dockerfile
  - name: dockerTag
    displayName: Target Container Tag Name
    type: string
    default: "opc-plc-simulator"

stages:
  - stage: development
    displayName: Development
    jobs:
      - job: build
        displayName: Build
        pool: IOT-Platform-Docker-Pool
        steps:
          - task: Docker@2
            displayName: Docker build and push
            inputs:
              containerRegistry: "IOT-Platform-Registry"
              repository: "opc-plc-dev"
              Dockerfile: ${{ parameters.dockerfilePath }}
              tags: ${{ parameters.dockerTag }}
