apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: default
spec:
  containers:
  - name: privileged-container
    image: ubuntu:latest  
    command: ["/bin/sleep", "3600"]  
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
