trigger:
  - none
# Starter pipeline
parameters:
  - name: dockerfileName
    displayName: Dockerfile Name
    type: string
    default: 'opc-plc.Dockerfile'
  - name: dockerTag
    displayName: Target Container Tag Name
    type: string
    default: 'opc-plc-simulator'

stages:
  - stage: development
    displayName: Development
    jobs:
      - job: build
        displayName: Build
        pool: IOT-Platform-Docker-Pool
        steps:
          - task: Docker@2
            displayName: Docker build and push
            inputs:
              containerRegistry: 'IOT-Platform-Registry'
              repository: 'opc-plc'
              Dockerfile: dockerfile/${{ parameters.dockerfileName }}
              tags: ${{ parameters.dockerTag }}
